version: "3.8"

services:
  web:
    container_name: micro-do-web-1
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/home/node/app/apps/web
      - ./packages:/home/node/app/packages
    environment:
      - NODE_ENV=development
    env_file:
      - ./dotenv/web.env

  api-gateway:
    container_name: micro-do-api-gateway-1
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api-gateway:/home/node/app/apps/api-gateway
      - ./packages:/home/node/app/packages
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./dotenv/api-gateway.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-do-network

  auth-service:
    container_name: micro-do-auth-service-1
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: development
    ports:
      - "3002:3002"
    volumes:
      - ./apps/auth-service:/home/node/app/apps/auth-service
      - ./packages:/home/node/app/packages
    environment:
      - NODE_ENV=development
      - PORT=3002
    env_file:
      - ./dotenv/auth-service.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-do-network

  tasks-service:
    container_name: micro-do-tasks-service-1
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
      target: development
    ports:
      - "3003:3003"
    volumes:
      - ./apps/tasks-service:/home/node/app/apps/tasks-service
      - ./packages:/home/node/app/packages
    environment:
      - NODE_ENV=development
      - PORT=3003
    env_file:
      - ./dotenv/tasks-service.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-do-network

  notifications-service:
    container_name: micro-do-notifications-service-1
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
      target: development
    ports:
      - "3004:3004"
    volumes:
      - ./apps/notifications-service:/home/node/app/apps/notifications-service
      - ./packages:/home/node/app/packages
    environment:
      - NODE_ENV=development
      - PORT=3004
    env_file:
      - ./dotenv/notifications-service.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-do-network

  db:
    image: postgres:18-alpine3.23
    container_name: micro-do-db-1
    attach: false
    ports:
      - "5432:5432"
    networks:
      - micro-do-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./dotenv/db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1.6-management-alpine
    container_name: micro-do-rabbitmq-1
    attach: false
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-do-network
    env_file:
      - ./dotenv/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  micro-do-network:
    driver: bridge
