version: "3.8"

services:
  web:
    container_name: jungle-do-web-1
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/home/node/app/apps/web
      - /home/node/app/node_modules
      - /home/node/app/apps/web/node_modules
    environment:
      - NODE_ENV=development

  api-gateway:
    container_name: jungle-do-api-gateway-1
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api-gateway:/home/node/app/apps/api-gateway
      - /home/node/app/node_modules
      - /home/node/app/apps/api-gateway/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./dotenv/api-gateway.env
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - jungle-do-network

  auth-service:
    container_name: jungle-do-auth-service-1
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: development
    ports:
      - "3002:3002"
    volumes:
      - ./apps/auth-service:/home/node/app/apps/auth-service
      - /home/node/app/node_modules
      - /home/node/app/apps/auth-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
    env_file:
      - ./dotenv/auth-service.env
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - jungle-do-network

  tasks-service:
    container_name: jungle-do-tasks-service-1
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
      target: development
    ports:
      - "3003:3003"
    volumes:
      - ./apps/tasks-service:/home/node/app/apps/tasks-service
      - /home/node/app/node_modules
      - /home/node/app/apps/tasks-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
    env_file:
      - ./dotenv/tasks-service.env
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - jungle-do-network

  notifications-service:
    container_name: jungle-do-notifications-service-1
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
      target: development
    ports:
      - "3004:3004"
    volumes:
      - ./apps/notifications-service:/home/node/app/apps/notifications-service
      - /home/node/app/node_modules
      - /home/node/app/apps/notifications-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3004
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - jungle-do-network

  db:
    image: postgres:18-alpine3.23
    container_name: jungle-do-db-1
    attach: false
    ports:
      - "5432:5432"
    networks:
      - jungle-do-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./dotenv/db.env

  rabbitmq:
    image: rabbitmq:4.1.6-management-alpine
    container_name: jungle-do-rabbitmq-1
    attach: false
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jungle-do-network
    env_file:
      - ./dotenv/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  jungle-do-network:
    driver: bridge
